# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='my location default text', max_length=128, null=True),
        ),
    ]
